# Conexión a Supabase
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Auth
jwt.secret=${JWT_SECRET:pL9#v&2Z!mQW4*rX9u@b7K$jE1nS6tY8^zH5vG3fA0xC7mP2qW9*kL4#vN1zR8uT6&jB}
jwt.expiration=28800000

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect